### ISSUE TITLE
What is the licence for the proj ? Also wat do you mean by app.js ? Node server?

### ISSUE THREAD

**Issue by pravin-d** [code-canvas/codeCanvas-Desktop#3]

**Comment by Glorycs29** [comment]
License: When creating a GitHub repository, you have the choice to choose a license template provided by GitHub, or you can select a license of your choice. It is important to select a license that aligns with your project's goals and requirements.
It gives us reliable and legal protection. 

App.js files: App. js is built to serve the makers of static single-page apps. This means that it keeps all page navigation within the session of the webpage, defining "pages" as DOM nodes that can be instantiated. Pages are HTML elements that have certain generic components like a topbar and content area.

Node server: Node. js is an open-source server environment. Node. js uses JavaScript on the server. The task of a web server is to open a file on the server and return the content to the client.

I hope this is helpful.
